# Generated by Django 2.2.1 on 2019-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('food_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=500)),

        
            ],
        ),
    ]
