# Generated by Django 2.2.1 on 2019-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('festival_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('ethinic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
