# Generated by Django 2.2.1 on 2019-05-16 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yatraapp', '0002_auto_20190514_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='festival',
            name='month',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='food',
            name='month',
            field=models.CharField(max_length=60),
        ),
    ]
