# Generated by Django 2.2.1 on 2019-05-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatraapp', '0004_auto_20190516_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='festival_image',
            new_name='festival_image_url',
        ),
    ]
