# Generated by Django 2.2.1 on 2019-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatraapp', '0005_auto_20190516_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activetttt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='month',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
