# Generated by Django 2.2.1 on 2019-06-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatraapp', '0007_auto_20190602_0818'),
        ('yatraapp', '0006_festival_month'),
    ]

    operations = [
    ]
