# Generated by Django 2.2.1 on 2019-06-02 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yatraapp', '0008_merge_20190602_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='festival',
            name='checkout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
